baseURL = 'https://blog.lislis.xyz'
languageCode = 'en-us'
title = 'blog.lislis.xyz'

theme = "hugo-theme-diary"

pygmentsCodeFences = true
pygmentsUseClasses = true                      

[Params.author]
    name = "lislis"
    website = "https://lislis.xyz"
    github = "lislis"
    mastodon = "https://toot.cat/@lislis"
    


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
